### ISSUE TITLE
1.20.1 Lavaspring cannot be picked up?

### ISSUE THREAD

**Issue by kingstairs** [kwpugh/resourceful_tools_fabric#10]
I was trying to pick up a Lavaspring block to move it. Using an End Gobber silk touch pickaxe. It took a very long time to break the block (much longer than obsidian I believe), but when it broke I got nothing back. I don't have another lavaspring to hand to see if this is a one-off or reproducible.

In 1.19.2 this did not happen (same mods, final 1.19.2 versions).

MC 1.20.1 Fabric, RT 1.5.1, Gobber2 2.9.3
Heavily modded instance, but I don't believe any of the other mods affect tools/mining/etc; I was using (almost) the same mods in 1.19.2.

**Comment by kwpugh** [comment]
I found the issue.  Somehow the lava spring and well spring were not in the mineable/pickaxes.json file so the game knows they can be mined with a pickaxe.

**Comment by kwpugh** [comment]
Fixed in next update
