### ISSUE TITLE
[22w11a] Gobber Ores will drop nothing if resourceful tools is installed

### ISSUE THREAD

**Issue by susan3333333** [kwpugh/resourceful_tools_fabric#3]
I have wiped and started over, one mod at a time, and the problem of Gobber ores not dropping occurs only when Resourceful tools is installed :(
The block is becomes very slow to break, and disappears without dropping anything.

**Comment by kwpugh** [comment]
what versions of Gobber and resourceful tools are you using?

which pickaxe are you using to break the ore?

**Comment by susan3333333** [comment]
I'm on the 1.19 snapshot, using iron & diamond picks

**Comment by kwpugh** [comment]
22w11a I presume?

**Comment by susan3333333** [comment]
Yes

**Comment by kwpugh** [comment]
Ok, I can confirm as well.   Now to figure out why.

**Comment by kwpugh** [comment]
This is proving to be beyond me, you can track the action here:  https://github.com/FabricMC/fabric/issues/2091

**Comment by kwpugh** [comment]
The Fabric folks fixed this and with test when an updated Fabric API is released.

**Comment by kwpugh** [comment]
I just tested on my end, the latest Fabric API fixes this issue.  Please confirm.
