### ISSUE TITLE
[1.18.2/1.19] Putting a Diamond Crack Hammer from Resourceful Tools mod in a Create Mixer causes crash

### ISSUE THREAD

**Issue by xRebellion** [kwpugh/resourceful_tools_fabric#4]
**Describe the Bug**
As the title suggests, putting a diamond crack hammer (Resourceful Tools) inside a Create mixer causes crash. I already reported this to Create Fabric but it seems like they weren't able to do anything about it due to some limitations. (https://github.com/Fabricators-of-Create/Create/issues/418)

**Reproduction Steps**
1. Build a powered Create mixer with basin
2. Insert Diamond Crack Hammer from Resourceful Tools to basin
3. Crash happens, and the world can no longer be opened as long as the crash remain

**Expected Result**
It should not have crashed

**Crash Report or Log**
https://pastebin.com/XCmkmcyj

**Minecraft Version**
1.18.2

**Comment by kwpugh** [comment]
I will take a look.  My private lib exists until fabric provides a more reliable option.
https://github.com/FabricMC/fabric/pull/1180

**Comment by kwpugh** [comment]
I don't play Create, what does the Mixer do?

**Comment by kwpugh** [comment]
Out of curiosity,  why would you put  a crack hammer in a Mixer?

**Comment by xRebellion** [comment]
> I don't play Create, what does the Mixer do?

The mixer allows for automation on all shapeless recipe

> Out of curiosity, why would you put a crack hammer in a Mixer?

Because I wanted to try to automate ore doubling with the hammer until I have a better way of doing so, since the AQM2 mod pack does not provide a rather easy automated solution on ore doubling

**Comment by kwpugh** [comment]
Ok, I think I may have a solution, but I have trouble testing with Create since it doesn't run on my slow computer.

Can you try this out.
[ResourcefulTools-Fabric-1.18.2-1.2.38.jar.zip](https://github.com/kwpugh/resourceful_tools_fabric-1.17/files/9073037/ResourcefulTools-Fabric-1.18.2-1.2.38.jar.zip)

**Comment by xRebellion** [comment]
Alright, I tried it. But it still doesn't work. Here's the crash log:
[crash-2022-07-08_22.10.34-server.txt](https://github.com/kwpugh/resourceful_tools_fabric-1.17/files/9073111/crash-2022-07-08_22.10.34-server.txt)

**Comment by kwpugh** [comment]
I've been  chatting with the developer of Create and it does not look like there  is a viable solution, that is  within my current programming  capability.  We will have to wait until the Fabric folks implement that PR mentioned above.

**Comment by xRebellion** [comment]
Alright then. I guess right now for the corrupt world I'll have to use an external world editor. Thank you

**Comment by kwpugh** [comment]
just disable the mod, go in a break the mixer, exit, then re-enable  the mod.

**Comment by kwpugh** [comment]
1.20.1 and later of Resourceful Tools no longer use the private lib causing the issue.
