### ISSUE TITLE
Cannot use hook knife in dispenser for string farm

### ISSUE THREAD

**Issue by kingstairs** [kwpugh/resourceful_tools_fabric#5]
I have an existing wool farm 🐑 (dispensers+shears), and I thought: 💡 "Hey, I can make some hook knives and add them to the dispensers to get some string alongside the wool!"

Unfortunately, when I did that, the hook knives just got dispensed, not used as the shears are. 😢 

🤔 I am guessing the item needs some additional tags or properties so dispensers can treat them like shears.

MC 1.19.2 (Fabric), mod version 1.3.19

**Comment by kwpugh** [comment]
Nope.  That is by intent.  The tools are designed for farming.
