### ISSUE TITLE
[suggestion} Make the water and lava wells into a "storage"/"Generation" Block

### ISSUE THREAD

**Issue by DerShendi** [kwpugh/resourceful_tools_fabric#6]
The lava and water well are a nice addition to the game but would be nice if you could use fluid pipes/hoppers/interfaces so that it works like a storage block (like the cooking for blockheads well)

**Comment by kwpugh** [comment]
Hi, that is something I have no plans of doing.  I did not intend to create a block to supply endless lava to automation, just buckets and powering vanilla furnaces.  I believe there may be other mods that do what you are looking for.
