### ISSUE TITLE
[1.19.2] Infinite loop on world save

### ISSUE THREAD

**Issue by top-sekret** [kwpugh/resourceful_tools_fabric#8]
Due to the `BrewingStandBlockEntityMixin`'s `writeNbt` hook, when saving the world chunks containing a brewing stand will load themselves, wasting a lot of CPU time and permanently looping the game.

I have a **lot** of mods, so this may possibly not be reproducible with just Resourceful Tools, however I believe `writeNbt` is not an adequate place to query for neighboring blocks. Perhaps it could be done in `tick` or something like that?

**Comment by kwpugh** [comment]
The brewing stand mixing has been changed to using tick() in the coming 1.21 release.
