### ISSUE TITLE
1.20.1 Bamboo recipes conflict with base recipes

### ISSUE THREAD

**Issue by kingstairs** [kwpugh/resourceful_tools_fabric#9]
In 1.20.x there are new official recipes for bamboo: 9x bamboo = bamboo block, but these conflict with the RT recipes (bamboo sheet).
Right now I cannot create bamboo blocks, only RT bamboo sheets. This is with REI or manually - should be very easy to reproduce.
The 1.20 RT bamboo -> leather recipes will need to be removed or re-defined.

MC 1.20.1 Fabric, RT 1.5.1

**Comment by kwpugh** [comment]
I'll take a look.  in the meantime, you can use polymorph for selecting amongst conflicting recipes

**Comment by kwpugh** [comment]
<img width="1340" alt="Screenshot 2024-02-25 at 9 11 13 AM" src="https://github.com/kwpugh/resourceful_tools_fabric/assets/8809210/38783b95-4c63-4676-a507-3bb90e92c255">

The polymorph mod is handy to have.

**Comment by kwpugh** [comment]
I have implemented the Hand Scraper approach from Veggie Way into Resourceful Tools to convert bamboo into bamboo sheets, which are then crafted into large bamboo sheets, and then smelted into vanilla leather.  No vanilla recipe conflicts

![Screenshot 2024-02-25 at 10 20 54 AM](https://github.com/kwpugh/resourceful_tools_fabric/assets/8809210/f3ddc39b-9681-41eb-9ca2-3fe9ecbca799)
![Screenshot 2024-02-25 at 10 21 30 AM](https://github.com/kwpugh/resourceful_tools_fabric/assets/8809210/7d0c5cd6-21c5-4471-bd41-beb414393cf4)

**Comment by kwpugh** [comment]
This will be in the next update

**Comment by kingstairs** [comment]
Last night I thought of an alternative recipe (no tools needed) - 6x bamboo (3 on each side) + 3x mushroom (middle column) - the mushroom fibers could "bind" with the bamboo fibers to create the (large?) bamboo sheet (or something ;-)). Mushrooms would probably have to all be the same type (brown/red) unless a recipe can specify "any mushroom", but you could add recipes using the nether 'shrooms.

**Comment by kwpugh** [comment]
Interesting idea.   

I want to eventually make something kinda similar to the real world process:

_"Bamboo leather is made by breaking down the cellulose fibers in bamboo plants and combining them with a natural resin. This process creates a strong, durable, and eco-friendly material that can be used to create a variety of products, including clothing, accessories, and home goods.

In addition, bamboo is an abundant resource that grows quickly and does not require the use of pesticides or fertilizers. It also requires less water than traditional crops, making it an ideal choice for arid regions. This leather is also biodegradable and does not contain any harmful chemicals."_

**Comment by kwpugh** [comment]
new versions of Veggie Way and Resourceful have been uploaded to curse forge.  Resourceful tools now uses the hand scraper process for leather making like in veggie way, and c: tags allow for common recipes
